version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: fakedb
      POSTGRES_USER: fakepostgres
      POSTGRES_PASSWORD: fakewestside
    ports:
      - '4231:5432'

#application.yml не нужен !т.к я указал проброс! запрос отправится на локалку 4231 а там автоматом в базу-контейнер(5432)
#если бд установлена локально значит порт 5432 занят(нельзя пробросить так 5432:5432)
# проброс порта  что каждая квартира в доме - это отдельный контейнер Docker, а почтовый ящик - это порт,
#  через который можно общаться с контейнером это как механизм маршрутизации сетевого трафика
#контейнеры автономные! просто так к ним не достучаться и нужно сделать связь между внешним миром и контейнером
# '4231:5432' - означает что если мы из внешнего мира хотим обратиться к бд контейнеру нам нужен port mapping
# отныне чтобы достучаться на порт 5432 внутри контейнера нам нужно обратиться через посредник 4231(наш локал)
# когда будем создавть настройки постгреса мы должны написать jdbc:postgresql://localhost:4231/fakedb
#запрос идет на локал и автоматом в контейнер!!!только так можно достучаться до контейнера






#spring-boot-docker-compose плюсы:
#можно самому не билдить и запускать компоус
#контейнер запускается с запуском приложения